server:
  port: 8080
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.106.193.185:3306/order?characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: 123456
      druid:
        username: root
        password: 123456
        initial-size: 5
        max-active: 10
        min-evictable-idle-time-millis: 100000
        validation-query: select 1
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.wbh.manage.model

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql